### ISSUE TITLE
[CI] Create NPM package publishing workflow

### ISSUE THREAD

**Issue by leecalcote** [layer5io/sistent#1]
#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Note for @leecalcote, as part of this issue, one or more secrets need to be defined.

// @nebula-aac FYI

**Comment by leecalcote** [comment]
Will be adding `NPM_PASS` and `NPM_USER` secrets....

**Comment by nebula-aac** [comment]
done for noq
