### ISSUE TITLE
[CI] GitHub Pages and CNAME?

### ISSUE THREAD

**Issue by hamza-mohd** [layer5io/sistent#101]
#### Current Behavior
In preparation for a website for this design system, a domain name is needed. 

#### Desired Behavior
Proposing: either ux.layer5.io or sistent.layer5.io as the CNAME for this design system's website.

#### Discussion
@Rexford74 @aabidsofi19 @nebula-aac @layer5io/layer5-io-maintainers, do you have opinions?

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by hamza-mohd** [comment]
Oh, I see that this issue is related to https://github.com/layer5io/sistent/issues/23

**Comment by pragyamishra56** [comment]
I can solve this issue plz assign me
