### ISSUE TITLE
Logo Needed for Sistent

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/sistent#103]
#### Description

The **logo** is needed for **Sistent** which aligns with the current theme of the Organization.

Here are some resources which may help you with inspiration for the logo:
- [Sistent Repository](https://github.com/layer5io/sistent)
- [Figma](https://www.figma.com/files/team/972159062361165490/Layer5?fuid=985940838624039218)
- [Brand-Kit](https://layer5.io/company/brand)

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by ptdatta** [comment]
@saurabh100ni Can I work on it?

**Comment by saurabh100ni** [comment]
Sure @ptdatta 😎🚀

**Comment by ptdatta** [comment]
@saurabh100ni @leecalcote @ritiksaxena124 What do you think about this logo?Like the background and color can changed.
![Screenshot from 2023-10-01 00-34-23](https://github.com/layer5io/sistent/assets/94271200/24d925a4-4471-45f3-a4f7-cafec62fb627)

**Comment by leecalcote** [comment]
Yes, I think you're onto something here, @ptdatta.

**Comment by ptdatta** [comment]
![image](https://github.com/layer5io/sistent/assets/94271200/d2001b03-8e44-4cd6-b33f-c862bd758e2c)
These are my final results. @leecalcote @saurabh100ni

**Comment by saurabh100ni** [comment]
@lee //
