### ISSUE TITLE
[components] Remove using `any`

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#106]
#### Current Behavior

In `components`, there are several usage of `any`, and while I agree that some properties may be hard to define, it is better in the longevity of this project to ensure that we move most of the type definitions to avoid this error. Since we also have the `pre-commit` to check for lint errors and format as needed, this will fail.

#### Expected Behavior

```bash
/workspaces/sistent/packages/components/src/custom/ErrorBoundary.tsx
  26:62  error  Unsafe assignment of an `any` value                 @typescript-eslint/no-unsafe-assignment
  36:62  error  Unsafe assignment of an `any` value                 @typescript-eslint/no-unsafe-assignment
  58:17  error  Unexpected any. Specify a different type            @typescript-eslint/no-explicit-any
  59:23  error  'any' overrides all other types in this union type  @typescript-eslint/no-redundant-type-constituents
  61:44  error  Unexpected any. Specify a different type            @typescript-eslint/no-explicit-any
  70:76  error  Unexpected any. Specify a different type            @typescript-eslint/no-explicit-any
  71:44  error  Unexpected any. Specify a different type            @typescript-eslint/no-explicit-any
```

Implementation:
 - Define type definition for `react-error-boundary` as there is none

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
  - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by captain-Akshay** [comment]
i would like to work on this please assign it to me !

**Comment by nebula-aac** [comment]
@captain-Akshay Hello I appreciate you reaching out, however the original package has been created from @aabidsofi19 and it would be better if you reach out to him for more clarification on the issue.

If he instead feels it is better to do it himself, he can respond as appropriately on this open issue.

**Comment by nebula-aac** [comment]
Partial work is done already on open PR: https://github.com/layer5io/sistent/pull/95

**Comment by nebula-aac** [comment]
This is current done and merged in master, however improvement is always good
