### ISSUE TITLE
[components] Create Activity Toolbar component

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#118]
Review existing implementation in Meshery Cloud.

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by sudhanshutech** [comment]
Existing implementation have:

- Expandable search, filter, view columns(of data-tables) and grid/table view(where required)
-

**Comment by toth2000** [comment]
@nebula-aac @sudhanshutech are you folks referring to this component below?
<img width="383" alt="image" src="https://github.com/layer5io/sistent/assets/65480420/ec15fdd8-8c84-4412-9bdc-80e9f7ef3b61">

**Comment by sudhanshutech** [comment]
@toth2000 no not in dashboard, except dashboard you will find in all other pages:
![image](https://github.com/layer5io/sistent/assets/90546692/68b81eab-d9db-4a45-93c4-d4d3f212ae7b)

**Comment by toth2000** [comment]
@sudhanshutech Can you help with the meshery cloud repo link?
