### ISSUE TITLE
Separate Filled and Outlined icons

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#12]
We have plenty of icons that we can separate into its own category, Filled and Outlined.

If the icon is outlined, name the icons with `Outlined`

If the icon is filled, do not name the icon with `Filled`, leave the name as default.

Currently work in progress to group icons

- [x]  `Add`
- [x] `Bell`
- [x] `Chat`
- [x] `Circle`
- [x] `Clone`
- [x] `Cloud`
- [x] `Component`
- [x] `Copy`
- [x] `CreateNew`
- [x] `Rectangle`
- [x] `TallRoundedRectangle`
- [ ] `DataObject`
- [ ] `Delete`
- [ ] `Deploy`
- [ ] `Designer`
- [ ] `Detail`
- [ ] `Chevron`
- [ ] `Favorite`
- [ ] `Filter`
- [ ] `Hierarchical`
- [ ] `Mesh`
- [ ] `Application`
- [ ] `PanTool`
- [ ] `Pattern`
- [ ] `Pod`
- [ ] `Redo`
- [ ] `Reset`
- [ ] `Ring`
- [ ] `Save`
- [ ] `Screentshot`
- [ ] `Settings`
- [ ] `Star`
- [ ] `Toolkit`
- [ ] `Touch`
- [ ] `Shapes`
- [ ] `Undeploy`
- [ ] `Undo`
- [ ] `Validate`
- [ ] `Visibility`
- [ ] `Visualizer`

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by nebula-aac** [comment]
Working branch: https://github.com/nebula-aac/sistent/tree/group-icons

**Comment by coder12git** [comment]
Hey @nebula-aac I want to work on this issue!

**Comment by nebula-aac** [comment]
@coder12git 

Hello thanks for reaching out. I believed I already grouped some of them icons listed above, but the rest of the SVG icons needs to be updated too accordingly.

Are you up for this task?

**Comment by coder12git** [comment]
> @coder12git
> 
> Hello thanks for reaching out. I believed I already grouped some of them icons listed above, but the rest of the SVG icons needs to be updated too accordingly.
> 
> Are you up for this task?

Yes @nebula-aac

**Comment by coder12git** [comment]
@nebula-aac so should I work on rest other icons? If yes, then please assign to me, so that I can start

**Comment by coder12git** [comment]
@leecalcote should I do this for rest other icons?

**Comment by leecalcote** [comment]
Sounds great, @coder12git 👍
