### ISSUE TITLE
[components] Export `ClickAwayListener`

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#127]
Tasks:

- [ ] Need to export `ClickAwayListener` in `components/src/index.tsx`

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by coder12git** [comment]
@nebula-aac I want to work on this

**Comment by Layak-Ali** [comment]
@nebula-aac can you please assign me this issue?

**Comment by coder12git** [comment]
@leecalcote please assign this  issue to me :)

**Comment by leecalcote** [comment]
Yep
