### ISSUE TITLE
[ci] Add a build step in GitHub Actions

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#150]
The build step only happens in the manual release flow.

When I added the `checks.yml` workflow, I neglected to add a build step to follow up.

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by Debaditya-Som** [comment]
@nebula-aac if granted, can i work on this particular issue?

**Comment by Debaditya-Som** [comment]
@nebula-aac I have given a PR #159 regarding this issue, kindly review this
