### ISSUE TITLE
[docs] Add build steps in `README.md`

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#151]
`README.md` is lacking information to build in the root project.

`Makefile` already includes the steps, but still need a small section to provide instructions on how to build.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources

- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
  - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Debaditya-Som** [comment]
@nebula-aac if granted, can i work on this particular issue?

**Comment by Debaditya-Som** [comment]
@nebula-aac I've made the necessary changes and have given a PR, kindly review it.
