### ISSUE TITLE
[components] CircularProgress

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#168]
#### Mockups

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by 35C4n0r** [comment]
Hey @nebula-aac 
Saw this: https://discuss.layer5.io/t/call-for-volunteers-two-new-website-projects-just-starting/4097
Would like to work on this issue.
If possible, please provide a description of what to do
