### ISSUE TITLE
[components]- Add more components/ functions

### ISSUE THREAD

**Issue by sudhanshutech** [layer5io/sistent#172]
Add components:

~- [ ] Under List: Add Listitem, ListItemButton, ListItemText, ListItemIcon~
~- [ ] Under Menu: Add all available sub components under it~
- [ ] Autocomplete - need a separate ticket for this item as there were Typescript errors
- [x] Link - create separate ticket please
- [ ] Debounce functionality - need a separate ticket in order to move this to a hooks library or utilities library

#### Mockups

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by Emmanuel-Sasere** [comment]
I want to work on these.
Is it available?

**Comment by Yashsharma1911** [comment]
Thanks for raising your hand @Emmanuel-Sasere yes you can work on it, @sudhanshutech can you help him here to move forward by including acceptance tests in the issue

**Comment by Emmanuel-Sasere** [comment]
Thanks for raising your hand @Emmanuel-Sasere yes you can work on it, @sudhanshutech can you help him here to move forward by including acceptance tests in the issue

Noted. On it.

**Comment by Emmanuel-Sasere** [comment]
This is my first time contributing to open source. Please put me through.  I'm finding it difficult to get this to my local machine. Please, where do I start?

**Comment by Yashsharma1911** [comment]
@coder12git would you like to put him in the right direction

**Comment by Emmanuel-Sasere** [comment]
@coder12git would you like to put him in the right direction ^^

It will be greatly appreciated, @coder12git @Yashsharma1911

**Comment by coder12git** [comment]
> @coder12git would you like to put him in the right direction ^^

Sure @Yashsharma1911

**Comment by coder12git** [comment]
> @coder12git would you like to put him in the right direction ^^
> 
> It will be greatly appreciated. @coder12git @Yashsharma1911 🙏🙏🙏

@Emmanuel-Sasere , I don't believe it's a "good first issue", and it's your first time too so i will say move to those issues that have "help-wanted" / "good-first" issues label.
For how to setup this project locally ,  check [here](https://discuss.layer5.io/t/unable-to-setup-sistent-project-locally/3860)

**Comment by Emmanuel-Sasere** [comment]
Thanks@coder12git

**Comment by Yashsharma1911** [comment]
@Emmanuel-Sasere does this help, did you find an issue to work on?

**Comment by Emmanuel-Sasere** [comment]
Not yet @Yashsharma1911

**Comment by coder12git** [comment]
@Emmanuel-Sasere would you like to work on this good-first-issue -> https://github.com/meshery/meshery/issues/9227

If yes, please comment on that issue, I will assign you 🚀

**Comment by Emmanuel-Sasere** [comment]
Yes, please  @coder12git
