### ISSUE TITLE
Add Github workflow for deployment preview

### ISSUE THREAD

**Issue by coder12git** [layer5io/sistent#183]
#### Current Behavior
Currently, we don't have any GitHub workflow defined for deployment preview of `Sistent` site.
Check this PR -> https://github.com/layer5io/sistent/pull/182

#### Desired Behavior

-> Add  GitHub workflow for deployment preview.

#### Mockups

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by coder12git** [comment]
// @leecalcote

**Comment by sudhanshutech** [comment]
I think @coder12git we need to add the workflow inside your  branch or otherwise we will having conflicts

**Comment by coder12git** [comment]
> I think @coder12git we need to add the workflow inside your branch or otherwise we will having conflicts

Okay, but is it possible to make an another branch in sistent dedicated for site? In this way we can merge my PR into that branch and then can do changes there.
