### ISSUE TITLE
[repo]: Fix `commitizen` to work properly when commiting

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#197]
#### Current Behavior

I set up the `commitizen` and `commitlint` to lint the commits that contributors make, however, this isn't working which means that any recent commits may not be working correctly when it comes to generating the `CHANGELOG` with Lerna.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
  - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sudhanshutech** [comment]
@nebula-aac : https://lerna.js.org/docs/troubleshooting#publish-command

**Comment by sudhanshutech** [comment]
I see the commitlint is working fine, then what's the issue here
