### ISSUE TITLE
[ repo ]: Configure `packages` to use `eslint-config-sistent`

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#248]
#### Mockups

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by Shiva953** [comment]
want to take this up, could you please describe the implementation/give some underlying context?
