### ISSUE TITLE
[components]: Create custom `FlipCard`

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#313]
Review existing implementation in Meshery UI

https://github.com/meshery/meshery/blob/master/ui/components/FlipCard.js

- [ ] Update `FlipCard.js` to use MUI v5 and its styles (inline or not)
- [ ] Update imports to use existing components in `sistent-components`
- [ ] Place custom component in `custom` directory, and export appropriately
- [ ] Ensure that the component works properly locally before pushing PR for testing

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by dragon-slayer875** [comment]
Would like to request assignment to this issue. I think I have successfully migrated the component on my local machine.
