### ISSUE TITLE
[svg] Setup `Jest`

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#33]
Setup `jest` for testing framework

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by nebula-aac** [comment]
Open PR https://github.com/layer5io/sistent/pull/34

**Comment by VaibhavMalik4187** [comment]
Are we also planning to add code coverage collection using Jest?

**Comment by nebula-aac** [comment]
Yes it is plan, just trying to roll out PRs one by one to not break anything
