### ISSUE TITLE
[components]: Create `Stepper` component

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#381]
#### Mockups

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by sudhanshutech** [comment]
@aabidsofi19 the stepper you created is reusable right ?
