### ISSUE TITLE
[components]: Create `CatalogFilter` component

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#385]
Component to migrate from:

https://github.com/meshery/meshery/blob/master/ui/components/CatalogFilter.js

- [ ] Define the interface for the props in `CatalogFilter`
- [ ] Ensure that the component is exported and working properly by testing locally

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by dragon-slayer875** [comment]
Hello. I have read the contributing guides and handbook.
I have managed to migrate this component on my fork of sistent.
I request to be assigned to this issue so we can work together towards resolving it.
