### ISSUE TITLE
[Docs] update `readme` and `contributing`

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#42]
Task: Update `README.md` and `CONTRIBUTING`

- [ ] Add some general information on how to get started with using this repo
- [ ] Update `CONTRIBUTING` document specifically to this repo workflow

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by akebu6** [comment]
@nebula-aac what needs to be done with this issue?

**Comment by akebu6** [comment]
I'd be up to working on it as long as you tell me what needs to be added

**Comment by leecalcote** [comment]
@akebu6 there is some discussion on this in the community Slack that you might want to hop into.

**Comment by akebu6** [comment]
@leecalcote is that in the documentation channel?
