### ISSUE TITLE
[CI] Revise docker workflow

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#45]
This workflow failed.

We are not using docker just yet, so either we need to disable the workflow until we decide how to use docker.

https://github.com/layer5io/sistent/actions/runs/5979785377

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by nebula-aac** [comment]
Temporarily done by disabling the workflow, but keeping this issue open for tracking

**Comment by leecalcote** [comment]
@VaibhavMalik4187, interested?

**Comment by nebula-aac** [comment]
I have it disabled for now. https://github.com/layer5io/sistent/actions/workflows/multi-platform.yml

**Comment by nebula-aac** [comment]
Close for now, as docker build is needed right now
