### ISSUE TITLE
[CI] Redundant `npm install` step in release workflow?

### ISSUE THREAD

**Issue by leecalcote** [layer5io/sistent#505]
#### Current Behavior

The current release workflow has two steps performing `npm install`. Is this necessary or is it a redundant step that might be eliminated?

https://github.com/layer5io/sistent/blob/f0b95c49ee7ccaa62789fd6aa7e49158d83fe731/.github/workflows/release.yml#L22

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Ok, gotcha.

**Comment by sudhanshutech** [comment]
I will see if this can fixed
