### ISSUE TITLE
[svg] Remove duplicated icon(s)

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#53]
After making changes to move some of the common icons into its own directory, one of the file was not removed.

This issue is to track any of the icons that weren't moved appropriately, and needs to be removed because it already existed in the directory.

`icons/BusIcon.tsx`

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
  - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by swastik959** [comment]
@nebula-aac can you assign this issue to me please

**Comment by rj2704** [comment]
Hi @nebula-aac 
Currently, I don't have any issues to work on. I can fix this. Can you please assign this issue to me?

**Comment by rj2704** [comment]
Hi, Is this problem still open?
Are there any updates on this issue?

**Comment by swastik959** [comment]
@rj2704 hi I am working on this issue

**Comment by rj2704** [comment]
Hi @swastik959, thanks for the update.

**Comment by Ghat0tkach** [comment]
@swastik959 update?

**Comment by nebula-aac** [comment]
update, no longer needed. in the midst of one of the PRs, I removed the icon file, this has already been grouped in the `Bus` directory now.
