### ISSUE TITLE
[components] Add more MUI components

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#56]
We need to add more components to `components`

- [ ] `ButtonGroup`
- [x] `Radio Group`
- [ ] `Select`
- [ ] `Switch`
- [ ] `Text Field`
- [x] `Toggle Button`
- [x] `Toggle Button Group`
- [ ] `Badge`
- [ ] `List`
- [ ] `Table`
- [ ] `Menu`
- [ ] `Card`
- [x] `Accordion`
- [x] `AccordionActions`
- [x] `AccordionDetails`
- [x] `AccordionSummary`
- [x] `AvatarGroup`
- [x] `Backdrop`
- [x] `Checkbox`
- [x] `Slide`

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by nebula-aac** [comment]
open PR for toggle button: https://github.com/layer5io/sistent/pull/57

**Comment by nebula-aac** [comment]
open PR for 10 more icons: https://github.com/layer5io/sistent/pull/62

**Comment by kunal70006** [comment]
I'd also like to take care of the remaining components @nebula-aac

**Comment by kunal70006** [comment]
added the remaining components in #67
