### ISSUE TITLE
[storybook] Create missing stories

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#60]
#### Mockups

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by kunal70006** [comment]
hey @nebula-aac I wanna work on this but when i'm cd'ing into design-systems and running yarn dev or yarn storybook, i'm getting this following error:
`Failed to resolve entry for package "@layer5/sistent-components". The package may have incorrect main/module/exports specified in its package.json`

can you help out?

**Comment by kunal70006** [comment]
I changed 
`import { BaseButton } from '@layer5/sistent-components';` to 
`import { BaseButton } from '@layer5/sistent-components/src/button';` and it's working, idk if this is the correct way to do it tho

**Comment by kunal70006** [comment]
seems like adding /src at the end of the import fixes everything, still not sure if its the correct way or not

**Comment by nebula-aac** [comment]
We haven't submitted an official release so the `button` you have changed from `basebutton` to `button` will need to be built and released

**Comment by kunal70006** [comment]
ah got it, can you assign this to me as well?
also do I have to refer to some mockups for stories or not?

**Comment by nebula-aac** [comment]
actually i'm not experiencing what you said

**Comment by kunal70006** [comment]
could be a windows issue?

**Comment by kunal70006** [comment]
open pr #68

**Comment by nebula-aac** [comment]
I will have to test your repo after you change it to review so I can check the imports.

It should be using the direct imports from the built packages, but since we haven't done an official release, doing this internal in a yarn workspace maybe allowing import towards the `src` directory, instead from the `dist` directory

**Comment by kunal70006** [comment]
yeah sure once i'm done with the stories, i'll change the pr status to review and ping you here, then you can check

**Comment by kunal70006** [comment]
by the way @nebula-aac this might become a huge PR as there are a lot of components to cover, should we let it be or do you want to break it down into smaller issues?

**Comment by nebula-aac** [comment]
just do some here and there

**Comment by nebula-aac** [comment]
done
