### ISSUE TITLE
Create the `red-orange` palette from `#B32700`

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#603]
#### Current Behavior

The existing `#B32700` has more of red-orangish range of hues.

If you were to take a look at the palette generator from the color above, the range doesn't meet in the `#ff0` red color.

https://maketintsandshades.com/#B32700

It would be better to create a `red-orange` palette to differentiate against the existing the new `red` palette

#### Mockups

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Sistent site](https://www.figma.com/file/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?type=design&node-id=596%3A5227&mode=design&t=8MExPykHN1vQFCTZ-1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by surajgjadhav** [comment]
Hi, 
can I work on this issue ?
