### ISSUE TITLE
Consolidate separate markdown renderers

### ISSUE THREAD

**Issue by dragon-slayer875** [layer5io/sistent#624]
#### Current Behavior

Currently, we use two Markdown renderers:
- RenderMarkdown
- RenderMarkdownTooltip

This was done at the time to avoid a change in functionality without reviewer availability.
But it has been reviewed since then, and now it is desired to be consolidated.

#### Expected Behavior

They can be consolidated into one by passing props instead, to make a single component.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
  - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Sistent site](https://www.figma.com/file/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?type=design&node-id=596%3A5227&mode=design&t=8MExPykHN1vQFCTZ-1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by dragon-slayer875** [comment]
// @sudhanshutech

**Comment by senthil-athiban** [comment]
@dragon-slayer875 , I would like to work on these issue.

**Comment by dragon-slayer875** [comment]
@senthil-athiban any updates here?

**Comment by senthil-athiban** [comment]
sorry for the delay @dragon-slayer875 , here is the [PR](https://github.com/layer5io/sistent/pull/715)

**Comment by leecalcote** [comment]
Issue and PR abandoned.
