### ISSUE TITLE
[Icon]: Add CatalogIcon from Layer5 brand page

### ISSUE THREAD

**Issue by dottharun** [layer5io/sistent#632]
#### Current Behavior
- There is no existing implementation for CatalogIcon from [brand page](https://layer5.io/company/brand) in sistent

#### Expected Behavior
- Add CatalogIcon into sistent, exported ready to use with color parameters.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
  - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Sistent site](https://www.figma.com/file/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?type=design&node-id=596%3A5227&mode=design&t=8MExPykHN1vQFCTZ-1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by 26vanshika** [comment]
Hey I wanna work on this issue but could you specify what type of Catalogicon are you looking for

**Comment by dottharun** [comment]
@26vanshika Thanks for showing interest in this issue,

- Please confirm that you have your local setup working after reading the [README](https://github.com/layer5io/sistent/blob/master/README.md) and [CONTRIBUTING.md](https://github.com/layer5io/sistent/blob/master/CONTRIBUTING.md).
- You can also explore issues with the label `good first issue` ([Meshery issues](https://github.com/meshery/meshery/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22), [Sistent issues](https://github.com/layer5io/sistent/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)) when they open up, to get more help.

Feel free to reach out if you need any assistance!

**Comment by 26vanshika** [comment]
Yeah I have set it up and have also explored other issues, if you could just guide me what type of Catalogico are you looking for primarily

**Comment by dottharun** [comment]
Yes, the brand page mentioned above has the assets you need. For the default fill colors, you can use Keppel and Charcoal as shown in the first example.

**Comment by 26vanshika** [comment]
Okay I will try to come uo with something

**Comment by 26vanshika** [comment]
Hey @dottharun, just a doubt the catalog icon should look like just like the one in meshery right?
<img width="1440" alt="Screenshot 2024-06-01 at 6 11 58 PM" src="https://github.com/layer5io/sistent/assets/115115186/218c0cb1-20d7-4f03-ad34-3f2d2539c9ea">

**Comment by dottharun** [comment]
@26vanshika Not sure which one you are referring to, but it's in the Catalog section of the [brand page](https://layer5.io/company/brand). Please use those assets.
- Also, look at the other [Icon Components](https://github.com/layer5io/sistent/tree/master/src/icons) in the codebase to get an idea of the parameters for the SVG.
