### ISSUE TITLE
Table creation for Color description on Sistent Color Page

### ISSUE THREAD

**Issue by Aviral0702** [layer5io/sistent#646]
#### Current Behavior
While going through the HTML code on the web browser on the Sistent's Identity Color page you can see that the color tables are images. Instead of the image it should be tables designed to show the various colors.

Link to reproduce the issue : https://layer5.io/projects/sistent/identity/color/code

![image](https://github.com/layer5io/sistent/assets/134831178/ccd482e2-811e-47db-b8fd-ea1567d374ad)

![image](https://github.com/layer5io/sistent/assets/134831178/27c2aeec-6584-44fc-a118-4c0e0fd73510)

#### Desired Behavior
The desired behavior should be such that the table must be represented as table only and not as an image. The color codes must be listed in a table.

#### Implementation
Working on this issue I will be converting the image date to the table format while keeping the data same and image of the colors intact.

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Sistent site](https://www.figma.com/file/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?type=design&node-id=596%3A5227&mode=design&t=8MExPykHN1vQFCTZ-1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by Rishikesh63** [comment]
i would like to work on this issue

**Comment by Muhammed-Moinuddin** [comment]
I would like to work on it.

**Comment by sudhanshutech** [comment]
This is not right place for this issue, i have already created a issue at layer5. please follow up on here:https://github.com/layer5io/layer5/issues/5668
