### ISSUE TITLE
[Component] Add 1 second delay to the disappearance of tooltips

### ISSUE THREAD

**Issue by leecalcote** [layer5io/sistent#647]
#### Current Behavior

When users try to hover over a [tooltip](https://github.com/layer5io/sistent/tree/master/src/base/Tooltip) to either copy information or to click a hyperlink, the tooltip often disappears before their mouse can reach the hyperlink or select text.

#### Desired Behavior

~1 second delay would be helpful.

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Sistent site](https://www.figma.com/file/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?type=design&node-id=596%3A5227&mode=design&t=8MExPykHN1vQFCTZ-1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by barkhaaroraa** [comment]
hi could i work on this issue?

**Comment by leecalcote** [comment]
Thanks for volunteering! I am assigning the issue in chronological order…

**Comment by sudhanshutech** [comment]
@barkhaaroraa any updates?

**Comment by leecalcote** [comment]
@dragon-slayer875, thanks for stepping up.
