### ISSUE TITLE
Pop up on components page

### ISSUE THREAD

**Issue by barkhaaroraa** [layer5io/sistent#651]
#### Current Behavior

There's this screen with a couple of buttons that pops up for a second, as visible in the video

#### Expected Behavior

no pop up should be there

#### Screenshots/Logs
![image](https://github.com/layer5io/sistent/assets/115429121/b56f42b8-4470-42f8-badc-aa42b9e299c9)
[screen-capture.webm](https://github.com/layer5io/sistent/assets/115429121/a1a2f386-0938-4580-a4fa-3a4fe1acee67)

#### Environment

- **Host OS:**Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
  - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Sistent site](https://www.figma.com/file/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?type=design&node-id=596%3A5227&mode=design&t=8MExPykHN1vQFCTZ-1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by kesharibhai84** [comment]
hii @barkhaaroraa ,please assign me this issue , i want to work on it.

**Comment by sudhanshutech** [comment]
@barkhaaroraa please open this issue in layer5 repo not here. I am closing here .
