### ISSUE TITLE
[UI] Horizontal scrolling, Dropdown and Table of Content button issue on small devices

### ISSUE THREAD

**Issue by Muhammed-Moinuddin** [layer5io/sistent#678]
#### Current Behavior
Horizontal scrolling issue (creating space on right side of screen), Dropdown not visible and Table of Content button not clicking/working on small devices

#### Expected Behavior
There should be not any horizontal scrolling (no-space on right side of screen), Dropdown should be visible(with proper working) and Table of Content button should be clickable and working.

I will work on this issue

#### Screenshots/Logs

https://github.com/user-attachments/assets/c2c57679-aa6d-4eaa-b001-08484ff28014

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
  - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Sistent site](https://www.figma.com/file/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?type=design&node-id=596%3A5227&mode=design&t=8MExPykHN1vQFCTZ-1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sudhanshutech** [comment]
@Muhammed-Moinuddin please open this issue in layer5 repo , not here.. And close this

**Comment by Muhammed-Moinuddin** [comment]
> @Muhammed-Moinuddin please open this issue in layer5 repo , not here.. And close this

Oops. Mistake.
Noted.
