### ISSUE TITLE
createAndEditWorkspace/uiSchema.tsx name issue

### ISSUE THREAD

**Issue by Muhammed-Moinuddin** [layer5io/sistent#681]
#### Current Behavior
Currently uiSchema of createAndEditWorkspace has wrong schema name (i.e.createAndEditEnvironmentUiSchema).

#### Expected Behavior
It should be createAndEditWorkspaceUiSchema, as it is imported and exported with that name.

#### Screenshots/Logs
![Screenshot from 2024-07-17 06-45-01](https://github.com/user-attachments/assets/cbb0a8b8-898f-44bd-9691-a213df63f76e)
![Screenshot from 2024-07-17 06-29-48](https://github.com/user-attachments/assets/01a8b71b-fc5c-4289-9095-305f63c2ff31)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
  - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Sistent site](https://www.figma.com/file/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?type=design&node-id=596%3A5227&mode=design&t=8MExPykHN1vQFCTZ-1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sudhanshutech** [comment]
@Muhammed-Moinuddin is this you already fixed right?
