### ISSUE TITLE
Remove `.golangci.yml`

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#7]
#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by singh1203** [comment]
@nebula-aac Is it a good first issue to solve if yes can I help to solve it?

**Comment by Layak-Ali** [comment]
hey @nebula-aac can you assign it to me?

**Comment by rj2704** [comment]
Hi @nebula-aac, I want to work on this issue. I can fix this. Can you please assign it to me.

**Comment by nakulbh** [comment]
@nebula-aac do you just want full file to be removed
