### ISSUE TITLE
[components] Create custom search bar

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#73]
In Meshery UI, we have created a search bar, but it is a mixture of Material UI v4 and MUI v5.

Here is the file for reference: https://github.com/meshery/meshery/blob/master/ui/components/searchcommon.js

There is a need to create a custom search bar in the `components` package to be reused.

At this time, there is not a default `ThemeProvider` in this repo, so at this, it would be great to create a custom search bar from the implementation in Meshery UI and display this in the Storybook for now.

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by harshal2030** [comment]
Hey, can I work on this

**Comment by nebula-aac** [comment]
This is done
