### ISSUE TITLE
[components] Create custom modal

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#74]
Requirements:

- [ ] Create a custom `Modal` using the custom `Dialog` or the base `Dialog` components exported from the `components` library.

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by coder12git** [comment]
@nebula-aac @leecalcote I would like to work on this issue

**Comment by sudhanshutech** [comment]
@aabidsofi19 i guess you were taking this to make the custom modal or generic modal

**Comment by sudhanshutech** [comment]
@Yashsharma1911
