### ISSUE TITLE
[Feature] Add box shadow to the tooltip component

### ISSUE THREAD

**Issue by leecalcote** [layer5io/sistent#747]
#### Current Behavior

The addition of a drop shadow to the tooltip component, would be great.

#### Implementation

```
box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
```

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Sistent site](https://www.figma.com/file/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?type=design&node-id=596%3A5227&mode=design&t=8MExPykHN1vQFCTZ-1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by Sumitsh28** [comment]
Hey @leecalcote, I want to work on this issue
