### ISSUE TITLE
[components] Create custom dialog

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#75]
#### Mockups

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by Vivek7038** [comment]
is there any guide how to start till project locally

**Comment by nebula-aac** [comment]
This is done here: https://github.com/layer5io/sistent/tree/master/packages/components/src/custom/Dialog
