### ISSUE TITLE
[components] Create custom Checkbox

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#77]
#### Current Behavior

Add a custom `Checkbox`

#### Desired Behavior

One of the requirements is to make sure that `Checkbox` is a reusable component, and derived from multiple Meshery repos, to try and combine the most common styles that are being used.

The first thing though is to allow the `Checkbox` to be generic to be reused. The styles can be applied through the theme that will be added later.

#### Mockups

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by ptdatta** [comment]
@nebula-aac  Can I work on it?
