### ISSUE TITLE
Create GitHub Actions to deploy npm packages

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#8]
#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by leecalcote** [comment]
Related to #1

**Comment by nebula-aac** [comment]
open issue already
