### ISSUE TITLE
[components] `Dialog` custom default styles

### ISSUE THREAD

**Issue by nebula-aac** [layer5io/sistent#96]
`Dialog` is being used and reused as a generic component.

- [ ] Define default styling for the `Dialog`
- [x] Create generic `Dialog` component

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by coder12git** [comment]
I want to work on this issue @nebula-aac

**Comment by nebula-aac** [comment]
@coder12git Hey there, thanks for expressing your interest.

I already have this done, but there is nothing wrong taking the extra step to make improvement to what I already have.
